### ISSUE TITLE
Model not found with these parameters : {"ProviderName":"OpenAI"}

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#65]
```
Import-AIProvider -Provider 'Anthropic' -ApiKey (ConvertTo-SecureString $env:AnthropicAPIKey -AsPlainText)

New-Agent -Provider OpenAI | Get-AgentResponse 'what is the capital of france'
```

![image](https://github.com/user-attachments/assets/145b1221-79e8-4c07-812a-6440514e58b4)

**Comment by Agazoth** [comment]
Did you import the OpenAI Provider? Whatr does Get-AIProvider -All return?

**Comment by Agazoth** [comment]
The current implementation behaves like this:

If no AIProviders have been imported, any attempt to call Get-AIProvider triggers New-ProviderListFromEnv which in turn imports AIProviders if the required variables are configured ($env:OpenAIKey for OpenAI and $script:AzOAISecrets['apiKEY'], $script:AzOAISecrets['deploymentName'], $script:AzOAISecrets['apiURI'] and  $script:AzOAISecrets['apiVersion'] fir AzureOpenAI) These 2 are the only 2 providers currently supported in New-ProviderListFromEnv. 

As soon as a single provider is in the list, New-ProviderListFromEnv does not get triggred automatically anymore.

We can absolutely expand on supporting users who prefer env variables and adjust the logic accordingly. We just need to agree on how to implement it: https://github.com/dfinke/PSAI/issues/54#issuecomment-2535428083

**Comment by dfinke** [comment]
Do you think the logic supports ease of use and no unintended side-effects?

**Comment by Agazoth** [comment]
I think it depends on the user.

If a user is looking for autoloading providers based on env variables, they should stick with that approach. And we need to solve https://github.com/dfinke/PSAI/issues/54#issuecomment-2535428083 to expand on the ability to load nore env variables.

If a user prefeers loading providers they want to work with, when they need to, thay can do so by running the Import-AIProvider cmdlet. That will work for those, who prefer that approach.

Mixing the 2 will work just fine if the user sets the desired env varaibles and strat using the module. If the user want to run additional providers after first run, they will have to import them with the Import-AIProvider cmdlet.

As soon as https://github.com/dfinke/PSAI/issues/54#issuecomment-2535428083 reaches a descion, New-ProviderListFromEnv can be updated to handle reruns and update providers based on whatever env variables they have configured since last run

**Comment by dfinke** [comment]
I like options and I don't like options. :-)

I think getting to a simple working solution for now and see how folks use it.

If I have to spend a bunch of time to get this experience. It'll take others much longer and they will punch out long before.

This needs to be simple and solid, then we can get to the meat of what the SDK offers. Like agents easily switching between o1 reasoning and claude haiku in the same script, for example.

Setup should no be a bottleneck.

```powershell
$swp = $WarningPreference
$WarningPreference = 'SilentlyContinue'

$null = Get-AIProviderList 
Import-AIProvider -Provider 'Anthropic' -ApiKey (ConvertTo-SecureString $env:AnthropicAPIKey -AsPlainText) -Force
Import-AIProvider -Provider Groq -ApiKey (ConvertTo-SecureString $env:GROQ_API_KEY -AsPlainText) -Force
# Import-AIProvider -Provider XAI -ApiKey (ConvertTo-SecureString $XAI_API_KEY -AsPlainText)
Import-AIProvider -Provider Gemini -ApiKey (ConvertTo-SecureString $env:GeminiKey -AsPlainText) -Force

$Providers = ((Get-AIProviderList). providers).keys

foreach ($Provider in $Providers) {
    [PSCustomObject][ordered]@{
        Provider = $Provider
        Response = New-Agent -Provider $Provider | Get-AgentResponse 'what is the capital of france'
    }
}

$swp = $WarningPreference
``

**Comment by Agazoth** [comment]
This is now handled in AIKeyInfo
